---
title: "nucleotide_diversity"
author: "Max McClure"
date: "2025-09-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir = "~/projects/eco_genomics_2025/population_genomics/myresults/ANGSD/diversity")
```

Import our libraries for plotting

```{r}
library(ggplot2)
library(tidyverse)

```

read in theta outputs

```{r}
theta <- read.table("2032_ALL_win50000_step50000.thetas", header = TRUE, sep = "\t")

```

```{r}
theta$tWsite = theta$tW/theta$nSites

theta$tPsite = theta$tP/theta$nSites
```

```{r}
theta2 <- theta %>%
  arrange(Chr, WinCenter) %>%
  filter(nSites > 100)

summary(theta2)
```

plotting histogram of total number of sites are in each seq window
```{r}
ggplot(data = theta2, aes(x = nSites)) +
  geom_histogram(bins = 50, fill = "lightblue", color = "black") +
  geom_vline(xintercept = median(theta2$nSites), color = "red", linetype = "dashed") +
  labs(title = "Distribution of windows with data", x = "Number of sites in 50kb window", y = "Frequency") 
```

plot pi

```{r}

ggplot(theta2, aes(x=Chr, y = tPsite, color = Chr)) +
  geom_point(size = 0.75, shape = 8, show.legend = FALSE) +
  ylim(0,0.07) +
  labs(title = "Nucleotide diversity in 50kb windows for population 2032", x = "Scaffold", y = "Theta-pi")

```


```{r}
ggplot(theta2, aes(x = tWsite, y = tPsite, color = Chr)) +
  geom_point(size = 0.75, shape = 8, show.legend = FALSE) +
  labs(title = "theta w and theta pi plotted against each other", x = "theta-W", y = "theta-pi") + 
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "black")
```


which windows have evidence of negative D and low nucleotide diversity ?
 - looking for selective sweep (demographic change), entire genome alteration
```{r}
theta2[which(theta2$Tajima<-1.5 & theta2$tPsite < 0.001),]
summary(theta2)
```





```{r}
mu = 2.5*10^-9
gen.time = 30
C = 4
mean_tW <- mean(theta2$tWsite)
mean_tP <- mean(theta2$tPsite)

Ne_theta <- mean_tW / (mu*gen.time*C)
Ne_theta
Ne_pi <- mean_tP / (mu*gen.time*C)
Ne_pi


sum(theta2$nSites)


maxD = max(theta2$Tajima)
minD = min(theta2$Tajima)

BigD <- theta2[which(theta2$Tajima == maxD),]

SmallD = theta2[which(theta2$Tajima == minD),]
SmallD
```












